INSERT INTO [dbo].[LengthConversion] ([ConName], [ToMeter]) VALUES (N'Centimeter', 100)
INSERT INTO [dbo].[LengthConversion] ([ConName], [ToMeter]) VALUES (N'Decameter', 0.1)
INSERT INTO [dbo].[LengthConversion] ([ConName], [ToMeter]) VALUES (N'Decimeter', 10)
INSERT INTO [dbo].[LengthConversion] ([ConName], [ToMeter]) VALUES (N'Foot', 3.28084)
INSERT INTO [dbo].[LengthConversion] ([ConName], [ToMeter]) VALUES (N'Hectmeter', 0.01)
INSERT INTO [dbo].[LengthConversion] ([ConName], [ToMeter]) VALUES (N'Inch', 39.3701)
INSERT INTO [dbo].[LengthConversion] ([ConName], [ToMeter]) VALUES (N'Kilometer', 0.001)
INSERT INTO [dbo].[LengthConversion] ([ConName], [ToMeter]) VALUES (N'Megameter', 1E-06)
INSERT INTO [dbo].[LengthConversion] ([ConName], [ToMeter]) VALUES (N'Meter', 1)
INSERT INTO [dbo].[LengthConversion] ([ConName], [ToMeter]) VALUES (N'Micrometer', 1000000)
INSERT INTO [dbo].[LengthConversion] ([ConName], [ToMeter]) VALUES (N'Mile', 0.000621371)
INSERT INTO [dbo].[LengthConversion] ([ConName], [ToMeter]) VALUES (N'Millimeter', 1000)
INSERT INTO [dbo].[LengthConversion] ([ConName], [ToMeter]) VALUES (N'Nautical Mile', 0.000539957)
INSERT INTO [dbo].[LengthConversion] ([ConName], [ToMeter]) VALUES (N'Yard', 1.0936132983)
